"""phase02_initial_19_models

Revision ID: c9a69f35eefa
Revises: 
Create Date: 2026-04-26 20:46:38.952167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a69f35eefa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='密钥名称/用途'),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='密钥哈希（不存明文）'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='密钥前缀（用于识别，如 mj_abc1）'),
    sa.Column('provider', sa.String(length=64), nullable=True, comment='kling/seedance/elevenlabs/fish 等'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='项目名称'),
    sa.Column('genre', sa.String(length=64), nullable=True, comment='题材（Revenge/Werewolf/Mafia/CEO）'),
    sa.Column('market', sa.String(length=32), nullable=True, comment='目标市场（US/UK/SEA）'),
    sa.Column('platform', sa.String(length=32), nullable=True, comment='目标平台（tiktok/douyin）'),
    sa.Column('tier', sa.String(length=16), nullable=True, comment='质量等级（S/SSS/A/B）'),
    sa.Column('budget_limit', sa.Float(), nullable=True, comment='预算上限（USD）'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='项目状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('episode_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('external_post_id', sa.String(length=128), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True, comment='完播率'),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('watch_time', sa.Float(), nullable=True, comment='总观看时长（秒）'),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False, comment='资产类型'),
    sa.Column('uri', sa.String(length=512), nullable=True, comment='文件路径或 URL'),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（bytes）'),
    sa.Column('duration', sa.Float(), nullable=True, comment='时长（秒，音视频用）'),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA256'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='角色名'),
    sa.Column('role_type', sa.String(length=32), nullable=True, comment='主角/配角/反派/路人'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('voice_profile', sa.JSON(), nullable=True, comment='声音配置（provider/voice_id/params）'),
    sa.Column('canonical_asset_id', sa.String(length=32), nullable=True, comment='代表资产 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('episode_no', sa.Integer(), nullable=False, comment='集号'),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True, comment='剧本大纲'),
    sa.Column('script', sa.Text(), nullable=True, comment='完整剧本'),
    sa.Column('duration', sa.Float(), nullable=True, comment='时长（秒）'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_cut_asset_id', sa.String(length=32), nullable=True, comment='当前剪辑版资产 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False, comment='regenerate_scene/generate_video/mix_audio/export 等'),
    sa.Column('target_type', sa.String(length=32), nullable=True, comment='scene/episode/asset'),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('worker_type', sa.String(length=32), nullable=True, comment='script/visual/audio/qa/edit/publish/ffmpeg'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending/running/completed/failed/cancelled'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cost_actual', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False, comment='success/failure/hook/rule/playbook'),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('config_value_json', sa.JSON(), nullable=True, comment='配置值（JSON）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='配置版本号'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('gate_code', sa.String(length=16), nullable=False, comment='G1a~G12'),
    sa.Column('subject_type', sa.String(length=32), nullable=False, comment='scene/scene_version/episode/asset'),
    sa.Column('subject_id', sa.String(length=32), nullable=False, comment='被检查对象 ID'),
    sa.Column('input_asset_id', sa.String(length=32), nullable=True, comment='本次检测输入资产'),
    sa.Column('evidence_asset_id', sa.String(length=32), nullable=True, comment='主证据资产'),
    sa.Column('step_key', sa.String(length=64), nullable=True, comment='image_gen/video_gen/mix/export'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending/passed/failed/needs_review'),
    sa.Column('score_json', sa.JSON(), nullable=True, comment='检测分数'),
    sa.Column('threshold_snapshot', sa.JSON(), nullable=True, comment='当时使用的阈值'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_bibles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='世界观/剧情设定内容'),
    sa.Column('beat_sheet', sa.JSON(), nullable=True, comment='节拍表（JSON）'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False, comment='scene/scene_version/qa_run/episode/publish_job'),
    sa.Column('owner_id', sa.String(length=32), nullable=False, comment='归属对象 ID'),
    sa.Column('relation_type', sa.String(length=32), nullable=True, comment='qa_input/qa_evidence/qa_report/cover/final 等'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False, comment='front/side/expression/reference'),
    sa.Column('asset_id', sa.String(length=32), nullable=True, comment='关联 assets.id'),
    sa.Column('uri', sa.String(length=512), nullable=True, comment='文件路径或 URL'),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False, comment='init/start/build_prompt/invoke_comfyui/upload_asset 等'),
    sa.Column('tool_name', sa.String(length=64), nullable=True, comment='comfyui/ffmpeg/kling_api 等'),
    sa.Column('input_json', sa.JSON(), nullable=True, comment='步骤输入参数'),
    sa.Column('output_json', sa.JSON(), nullable=True, comment='步骤输出结果'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='fallback_records 等'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publish_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('episode_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True, comment='tiktok/douyin'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True, comment='发布参数'),
    sa.Column('external_post_id', sa.String(length=128), nullable=True, comment='平台返回的帖子 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('qa_run_id', sa.String(length=32), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=False, comment='问题代码'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='critical/warning/info'),
    sa.Column('message', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('evidence_asset_id', sa.String(length=32), nullable=True),
    sa.Column('related_asset_id', sa.String(length=32), nullable=True, comment='问题直接关联资产'),
    sa.Column('related_scene_version_id', sa.String(length=32), nullable=True, comment='问题归属版本'),
    sa.Column('suggested_action', sa.Text(), nullable=True, comment='建议修复动作'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qa_run_id'], ['qa_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('scene_no', sa.Integer(), nullable=False, comment='镜头序号'),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True, comment='时长（秒）'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locked_version_id', sa.String(length=32), nullable=True, comment='锁定版本 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publish_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('publish_job_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('cover_asset_id', sa.String(length=32), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False, comment='是否选中用于发布'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publish_job_id'], ['publish_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True, comment='父版本 ID（用于版本链追踪）'),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('prompt_bundle', sa.JSON(), nullable=True, comment='Prompt 包（正面/负面/风格/参数）'),
    sa.Column('model_bundle', sa.JSON(), nullable=True, comment='模型包（生图/视频/音频模型配置）'),
    sa.Column('params', sa.JSON(), nullable=True, comment='其他参数（分辨率/帧率/种子等）'),
    sa.Column('change_reason', sa.String(length=512), nullable=True, comment='变更原因'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='GENERATING/QA_PASSED/NEEDS_REVIEW/MANUAL_APPROVED/LOCKED/DELIVERED'),
    sa.Column('score_snapshot', sa.JSON(), nullable=True, comment='QA 分数快照'),
    sa.Column('cost_actual', sa.Float(), nullable=True, comment='实际成本（USD）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_manju_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_manju_meta',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('scene_versions')
    op.drop_table('publish_variants')
    op.drop_table('scenes')
    op.drop_table('qa_issues')
    op.drop_table('publish_jobs')
    op.drop_table('job_steps')
    op.drop_table('character_assets')
    op.drop_table('asset_links')
    op.drop_table('story_bibles')
    op.drop_table('qa_runs')
    op.drop_table('project_configs')
    op.drop_table('knowledge_items')
    op.drop_table('jobs')
    op.drop_table('episodes')
    op.drop_table('characters')
    op.drop_table('assets')
    op.drop_table('analytics_snapshots')
    op.drop_table('projects')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
